<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXkOwkSG\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXkOwkSG/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXkOwkSG.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXkOwkSG\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXkOwkSG\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XkOwkSG',
    'container.build_id' => 'ba193d4a',
    'container.build_time' => 1521455350,
));
